#!/bin/sh

##### General #####

# Disable Crash Reporter
defaults write com.apple.CrashReporter DialogType -string "none"

# Disable Resume (Saved Application State) system-wide
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# Require password immediately after screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Show battery life as percentage
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

##### App Store #####

# Enable automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for updates daily
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download available updates in the background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install system data files and security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Enable auto-update
defaults write com.apple.commerce AutoUpdate -bool true

# Allow to restart the computer when required
defaults write com.apple.commerce AutoUpdateRestartRequired -bool true

##### Dashboard #####

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Don’t show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

##### Dialogs #####

# Show the shutdown dialog when power button is pressed
defaults write com.apple.loginwindow PowerButtonSleepsSystem -bool false

# Disable the 'Are you sure you want to open this application?' dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

##### Dock #####

# Wipe all icons
defaults write com.apple.dock persistent-apps -array

# Set the icon size to 60 pixels
defaults write com.apple.dock tilesize -int 60

# Lock the icon size
defaults write com.apple.Dock size-immutable -bool yes

# Change minimize/maximize window effect to 'scale'
defaults write com.apple.dock mineffect -string "scale"

# Minimize windows into application icon
defaults write com.apple.dock minimize-to-application -bool true

# Don't animate opening applications
defaults write com.apple.dock launchanim -bool false

# Show indicator lights for open applications
defaults write com.apple.dock show-process-indicators -bool true

# Stop icons from bouncing
defaults write com.apple.dock no-bouncing -bool true

##### Finder #####

# Set $HOME as the default location for new windows
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://$HOME"

# Display full path as window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Use list view in all windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Show all file extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Hide path bar
defaults write com.apple.finder ShowPathbar -bool false

# Don't show recent tags on sidebar
defaults write com.apple.finder ShowRecentTags -bool false

# Search only the current folder
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable window and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Enable quitting via Cmd + Q
defaults write com.apple.finder QuitMenuItem -bool true

# Show external drives, removable media and connected servers on Desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true

# Enable spring loading for folders
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Decrease the spring loading delay for folders
defaults write NSGlobalDomain com.apple.springing.delay -float 0.15

##### Keyboard #####

# Disable press and hold option to enable the repetition of keys
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Increase key repeat rate and decrease initial delay
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Disable automatic spelling correction and capitalization
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable automatic period, quote and dash substitution
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

##### Screenshots #####

# Save to Downloads
defaults write com.apple.screencapture location "$HOME/Downloads/"

# Save in PNG
defaults write com.apple.screencapture type -string "png"

# Disable shadow
defaults write com.apple.screencapture disable-shadow -bool true

##### TextEdit #####

# Use plain text mode for new files
defaults write com.apple.TextEdit RichText -int 0

# Open and save files as UTF-8
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

##### USB Volumes #####

# Automatically open a new window when a volume is mounted
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true

# Avoid creating .DS_Store files on USB volumes and networks
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
