window:
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  startup_mode: Fullscreen

font:
  size: 14.0
  offset:
    x: 1
    y: 5
  glyph_offset:
    y: 3

colors:
  primary:
    background: "0x282c34"
    foreground: "0xabb2bf"
  cursor:
    text:       "0x5c6370"
    cursor:     "0xabb2bf"
  normal:
    black:      "0x282c34"
    red:        "0xe06c75"
    green:      "0x98c379"
    yellow:     "0xe5c07b"
    blue:       "0x61afef"
    magenta:    "0xc678dd"
    cyan:       "0x56b6c2"
    white:      "0xabb2bf"
  bright:
    black:      "0x4b5263"
    red:        "0xbe5046"
    green:      "0x98c379"
    yellow:     "0xd19a66"
    blue:       "0x61afef"
    magenta:    "0xc678dd"
    cyan:       "0x56b6c2"
    white:      "0x3e4452"

mouse:
  hide_when_typing: true
